name: Build Triton

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main-windows
      python_minor:
        description: Python minor version
        required: true
        type: string
        default: '12'
      python_patch:
        description: Python patch version
        required: true
        type: string
        default: '9'

jobs:
  build-triton:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.${{ inputs.python_minor }}.${{ inputs.python_patch }}

      # - uses: Jimver/cuda-toolkit@v0.2.22

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build Triton
        shell: pwsh
        run: |
          # Get-ChildItem Env:

          # Get-Command -All python
          # python --version
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel

          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/triton-windows.git
          cd triton-windows
          git rev-parse HEAD

          $Env:TRITON_BUILD_BINARY = "0"
          $Env:TRITON_BUILD_PROTON = "0"
          $Env:TRITON_BUILD_UT = "0"
          $Env:CIBW_BUILD = "{cp3${{ inputs.python_minor }}-win_amd64,}"
          $Env:CIBW_BUILD_VERBOSITY = "1"
          cibuildwheel python

      - uses: actions/upload-artifact@v4
        with:
          path: triton-windows/wheelhouse/*
