name: COPILOT  Build SageAttention 2.2 (Windows • cu129 • Py3.13.7 • Torch 2.8 via Conda CUDA)

on:
  workflow_dispatch:
    inputs:
      sage_repo:
        description: "Upstream SageAttention repository"
        required: false
        default: "thu-ml/SageAttention"
      sage_ref:
        description: "Ref in upstream repo (branch/tag/sha). Use 'main' for 2.2 code."
        required: false
        default: "main"
      wheel_suffix:
        description: "Optional wheel filename suffix (e.g. +rev1)"
        required: false
        default: ""
      runner_label:
        description: "Runner label to use (e.g. windows-2022 or self-hosted)"
        required: false
        default: "windows-2022"

permissions:
  contents: read

jobs:
  build-win:
    name: Build wheel (Win, Py 3.13.7, Torch 2.8.0+cu129, CUDA toolkit via conda)
    # runner_label can be set to "windows-2022" (GH-hosted) or "self-hosted" / "self-hosted, windows"
    runs-on: ${{ github.event.inputs.runner_label }}
    timeout-minutes: 120

    env:
      PYTHON_VERSION: "3.13.7"
      TORCH_VERSION: "2.8.0"
      TORCH_CUDA_TAG: "cu129"
      TORCH_CUDA_ARCH_LIST: "8.9"
      FORCE_CUDA: "1"
      EXT_PARALLEL: "4"
      NVCC_APPEND_FLAGS: "--threads 8"
      MAX_JOBS: "8"
      CMAKE_GENERATOR: "Ninja"
      EXTRA_WHEEL_SUFFIX: "${{ github.event.inputs.wheel_suffix }}"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout SageAttention upstream
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.sage_repo }}
          ref: ${{ github.event.inputs.sage_ref }}
          path: SageAttention
          fetch-depth: 1

      - name: Show repository tree (debug)
        shell: pwsh
        run: |
          Get-ChildItem -Force -Recurse -Depth 1 | Format-List Name,Mode,Length
          Get-ChildItem -Path SageAttention -Force | Format-List Name,Mode,Length

      - name: Set up Miniconda (Py ${{ env.PYTHON_VERSION }})
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: buildenv
          python-version: ${{ env.PYTHON_VERSION }}
          channels: conda-forge,defaults
          miniforge-version: latest

      - name: Conda info / Python version
        shell: pwsh
        run: |
          conda info
          python --version

      - name: Install CUDA toolkit 12.9 (conda)
        if: ${{ always() }}
        shell: pwsh
        run: |
          conda install -y -c nvidia cuda-toolkit=12.9
          & nvcc --version

      - name: Upgrade build tooling
        shell: pwsh
        run: |
          python -m pip install -U pip setuptools wheel ninja cmake packaging

      - name: Install PyTorch ${{ env.TORCH_VERSION }} + ${{ env.TORCH_CUDA_TAG }}
        shell: pwsh
        run: |
          python -m pip install --index-url https://download.pytorch.org/whl/${{ env.TORCH_CUDA_TAG }} "torch==${{ env.TORCH_VERSION }}+${{ env.TORCH_CUDA_TAG }}" || Write-Host "Torch install may have failed — check availability for Py ${env:PYTHON_VERSION} and ${env:TORCH_CUDA_TAG}"
          python - << 'PY'
          import torch, sys, os
          print("Torch:", getattr(torch, '__version__', 'not installed'), "CUDA:", getattr(torch.version, 'cuda', 'unknown'), "Py:", sys.version)
          print("CUDA_HOME:", os.environ.get("CUDA_HOME") or os.environ.get("CUDA_PATH") or "")
          PY

      - name: Export CUDA env (Windows)
        shell: pwsh
        run: |
          $ENV:CUDA_HOME = "$ENV:CONDA_PREFIX"
          $ENV:CUDA_PATH = "$ENV:CONDA_PREFIX"
          $ENV:PATH = "$ENV:CONDA_PREFIX\Library\bin;$ENV:CONDA_PREFIX\bin;$ENV:PATH"
          echo "CUDA_HOME=$ENV:CUDA_HOME" >> $Env:GITHUB_ENV
          echo "CUDA_PATH=$ENV:CUDA_PATH" >> $Env:GITHUB_ENV
          echo "PATH=$ENV:PATH"         >> $Env:GITHUB_ENV

      - name: Show toolchain versions
        shell: pwsh
        run: |
          python --version
          & nvcc --version
          cl 2>$null | Select-Object -First 1
          Write-Host "CUDA_HOME=$ENV:CUDA_HOME"
          Write-Host "CUDA_PATH=$ENV:CUDA_PATH"
          Write-Host "TORCH_CUDA_ARCH_LIST=$ENV:TORCH_CUDA_ARCH_LIST"

      - name: Build SageAttention wheel (cp313-win_amd64)
        shell: pwsh
        working-directory: SageAttention
        env:
          TORCH_CUDA_ARCH_LIST: ${{ env.TORCH_CUDA_ARCH_LIST }}
          FORCE_CUDA: ${{ env.FORCE_CUDA }}
          EXT_PARALLEL: ${{ env.EXT_PARALLEL }}
          NVCC_APPEND_FLAGS: ${{ env.NVCC_APPEND_FLAGS }}
          MAX_JOBS: ${{ env.MAX_JOBS }}
          CMAKE_GENERATOR: ${{ env.CMAKE_GENERATOR }}
        run: |
          # Build wheel (setup.py expected). If your project uses pyproject.toml, replace with build backend.
          python setup.py bdist_wheel
          Get-ChildItem -Path dist | Format-List Name,Length

      - name: Add wheel suffix (optional)
        if: ${{ env.EXTRA_WHEEL_SUFFIX != '' }}
        shell: pwsh
        working-directory: SageAttention/dist
        run: |
          $wheels = Get-ChildItem -Filter "*.whl"
          foreach ($w in $wheels) {
            $new = $w.Name -replace '\.whl$', "${{ env.EXTRA_WHEEL_SUFFIX }}.whl"
            Rename-Item -Path $w.FullName -NewName $new
            Write-Host "Renamed: $($w.Name) -> $new"
          }

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: sageattention-2.2-cu129-win-py313
          path: SageAttention/dist/*.whl
          if-no-files-found: error
