name: PERPLEXITY_V3 Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag or branch to build from
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '8' # 2.8.x
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '0' # 2.8.0
      torch_is_nightly:
        description: PyTorch is nightly (1=yes, 0=no)
        required: true
        type: string
        default: '0'
      cuda_major:
        description: CUDA major version
        required: true
        type: string
        default: '12'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '9' # CUDA 12.9
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '0'
      extra_cuda_arch:
        description: Extra CUDA arch (space-separated, e.g. "8.0 8.6")
        required: false
        type: string
        default: ''
      extra_wheel_version_suffix:
        description: Extra wheel version suffix (e.g. ".post1")
        required: false
        type: string
        default: ''
      is_python_abi3:
        description: Build as Python ABI3 (non-empty to enable)
        required: false
        type: string
        default: ''

jobs:
  build-sageattn:
    runs-on: windows-latest  # changed from windows-large
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      # Install CUDA 12.x (12.9.x from inputs)
      - uses: N-Storm/cuda-toolkit@v0.2.28
        with:
          cuda: ${{ inputs.cuda_major }}.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          $Env:CUDA_MAJOR_VERSION = "${{ inputs.cuda_major }}"
          $Env:CUDA_MINOR_VERSION = "${{ inputs.cuda_minor }}"
          $Env:TORCH_MINOR_VERSION = "${{ inputs.torch_minor }}"
          $Env:TORCH_PATCH_VERSION = "${{ inputs.torch_patch }}"
          $Env:TORCH_IS_NIGHTLY = "${{ inputs.torch_is_nightly }}"

          python update_pyproject.py

          $Env:PIP_INDEX_URL = "https://pypi.org/simple"
          $Env:PIP_EXTRA_INDEX_URL = "https://download.pytorch.org/whl/cu129"

          $Env:DISTUTILS_USE_SDK = "1"

          $Env:TORCH_CUDA_ARCH_LIST = " 8.9"
          if (($Env:CUDA_MAJOR_VERSION -gt "12") -or ($Env:CUDA_MINOR_VERSION -gt "6")) {
            $Env:TORCH_CUDA_ARCH_LIST += "12.0 "
          }
          $Env:TORCH_CUDA_ARCH_LIST += "${{ inputs.extra_cuda_arch }}"

          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX = "+cu${{ inputs.cuda_major }}${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX += "${{ inputs.extra_wheel_version_suffix }}"

          if ("${{ inputs.is_python_abi3 }}") {
            $Env:CIBW_BUILD = "{cp312-win_amd64,}"
          }
          else {
            if ($Env:TORCH_MINOR_VERSION -gt "8") {
              $Env:CIBW_BUILD = "{cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64,cp314-win_amd64}"
            }
            elseif ($Env:TORCH_MINOR_VERSION -gt "5") {
              $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64}"
            }
            else {
              $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64}"
            }
          }

          $Env:CIBW_BUILD_VERBOSITY = "1"

          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
