name: CLAUDE Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: v2.2.0
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '8'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '0'
      torch_is_nightly:
        description: PyTorch is nightly
        required: true
        type: string
        default: '0'
      cuda_major:
        description: CUDA major version
        required: true
        type: string
        default: '12'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '9'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '0'
      extra_cuda_arch:
        description: Extra CUDA arch
        required: false
        type: string
        default: ''
      extra_wheel_version_suffix:
        description: Extra wheel version suffix
        required: false
        type: string
        default: ''
      is_python_abi3:
        description: Is Python ABI3
        required: false
        type: string
        default: ''

jobs:
  build-sageattn:
    runs-on: windows-large
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: N-Storm/cuda-toolkit@v0.2.28
        with:
          cuda: ${{ inputs.cuda_major }}.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      # Optionally checkout your repo if needed
      # - uses: actions/checkout@v4

      - name: Build wheel
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/thu-ml/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          $Env:CUDA_MAJOR_VERSION = "${{ inputs.cuda_major }}"
          $Env:CUDA_MINOR_VERSION = "${{ inputs.cuda_minor }}"
          $Env:TORCH_MINOR_VERSION = "${{ inputs.torch_minor }}"
          $Env:TORCH_PATCH_VERSION = "${{ inputs.torch_patch }}"
          $Env:TORCH_IS_NIGHTLY = "${{ inputs.torch_is_nightly }}"

          python update_pyproject.py

          Start-Process -NoNewWindow simpleindex simpleindex.toml
          Start-Sleep -Seconds 5  # Wait before continuing

          $Env:PIP_INDEX_URL = "http://127.0.0.1:8000"
          $Env:DISTUTILS_USE_SDK = "1"

          $Env:TORCH_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0 "
          if (([int]$Env:CUDA_MAJOR_VERSION -gt 12) -or ([int]$Env:CUDA_MINOR_VERSION -gt 6)) {
            $Env:TORCH_CUDA_ARCH_LIST += "12.0 "
          }
          $Env:TORCH_CUDA_ARCH_LIST += "${{ inputs.extra_cuda_arch }}"

          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX = "+cu${{ inputs.cuda_major }}${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX += "${{ inputs.extra_wheel_version_suffix }}"

          if ("${{ inputs.is_python_abi3 }}") {
            $Env:CIBW_BUILD = "cp310-win_amd64"
          }
          else {
            if ([int]$Env:TORCH_MINOR_VERSION -gt 8) {
              $Env:CIBW_BUILD = "cp310-win_amd64 cp311-win_amd64 cp312-win_amd64 cp313-win_amd64 cp314-win_amd64"
            }
            elseif ([int]$Env:TORCH_MINOR_VERSION -gt 5) {
              $Env:CIBW_BUILD = "cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64 cp313-win_amd64"
            }
            else {
              $Env:CIBW_BUILD = "cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64"
            }
          }

          $Env:CIBW_BUILD_VERBOSITY = "1"
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
